# Databricks notebook source
# MAGIC %sql
# MAGIC CREATE DATABASE IF NOT EXISTS RETAIL_FORECAST_ENGINE;

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS RETAIL_FORECAST_ENGINE.CHAMPION_MODELS
# MAGIC (
# MAGIC     RETAILER STRING,
# MAGIC     CLIENT STRING,
# MAGIC     COUNTRY_CODE STRING,
# MAGIC     ORGANIZATION_UNIT_NUM STRING,
# MAGIC     RETAILER_ITEM_ID STRING,
# MAGIC     MODEL_METADATA STRING,
# MAGIC     TRAINING_ID STRING,
# MAGIC     MODEL_ID STRING,
# MAGIC     MODEL_OBJECT BINARY,
# MAGIC     COLUMN_NAMES STRING,
# MAGIC     TEST_DAYS_COUNT INT,
# MAGIC     TRAIN_NON_ZERO_DAYS INT,
# MAGIC     TRAIN_DAYS_COUNT INT,
# MAGIC     METRICS_RMSE_TEST FLOAT,
# MAGIC     METRICS_MSE_TEST FLOAT,
# MAGIC     METRICS_R2_TEST FLOAT,
# MAGIC     OBSERVED_DATE_RANGE_MIN DATE,
# MAGIC     OBSERVED_DATE_RANGE_MAX DATE,
# MAGIC     DATE_MODEL_TRAINED TIMESTAMP,
# MAGIC     DATE_MADE_CHAMPION TIMESTAMP
# MAGIC )
# MAGIC USING DELTA
# MAGIC PARTITIONED BY (RETAILER, CLIENT, COUNTRY_CODE)

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS RETAIL_FORECAST_ENGINE.MODEL_TRAINING_RESULTS
# MAGIC (
# MAGIC     TRAINING_ID STRING,
# MAGIC     RETAILER STRING,
# MAGIC     CLIENT STRING,
# MAGIC     COUNTRY_CODE STRING,
# MAGIC     ORGANIZATION_UNIT_NUM STRING,
# MAGIC     RETAILER_ITEM_ID STRING,
# MAGIC     MODEL_METADATA STRING,
# MAGIC     COLUMN_NAMES STRING,
# MAGIC     TEST_NON_ZERO_DAYS INT,
# MAGIC     TEST_DAYS_COUNT INT,
# MAGIC     TRAIN_NON_ZERO_DAYS INT,
# MAGIC     TRAIN_DAYS_COUNT INT,
# MAGIC     MODEL_ID STRING,
# MAGIC     TEST_SET_MASE_PERFORMANCE FLOAT,
# MAGIC     OBSERVED_DATE_RANGE_MIN DATE,
# MAGIC     OBSERVED_DATE_RANGE_MAX DATE,
# MAGIC     DATE_MODEL_TRAINED TIMESTAMP
# MAGIC )
# MAGIC USING DELTA
# MAGIC PARTITIONED BY (RETAILER, CLIENT, COUNTRY_CODE)

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS RETAIL_FORECAST_ENGINE.DRFE_FORECAST_BASELINE_UNIT
# MAGIC (
# MAGIC     HUB_ORGANIZATION_UNIT_HK STRING,
# MAGIC     HUB_RETAILER_ITEM_HK STRING,
# MAGIC     LOAD_TS TIMESTAMP,
# MAGIC     RECORD_SOURCE_CD STRING,
# MAGIC     BASELINE_POS_ITEM_QTY DECIMAL(15,2),
# MAGIC     MODEL_ID STRING,
# MAGIC     SALES_DT DATE
# MAGIC )
# MAGIC USING DELTA
# MAGIC PARTITIONED BY (SALES_DT)

# COMMAND ----------

# MAGIC %md
# MAGIC ###DDL

# COMMAND ----------

# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS RETAIL_FORECAST_ENGINE.PERFORMANCE;
# MAGIC CREATE TABLE RETAIL_FORECAST_ENGINE.PERFORMANCE
# MAGIC      (ORGANIZATION_UNIT_NUM STRING,
# MAGIC     RETAILER_ITEM_ID STRING,
# MAGIC     RETAILER_ITEM_DESC STRING,
# MAGIC     RETAILER STRING,
# MAGIC     CLIENT STRING,
# MAGIC     COUNTRY_CODE STRING,
# MAGIC     SALES_DT DATE,
# MAGIC     POS_ITEM_QTY FLOAT,
# MAGIC     POS_AMT FLOAT,
# MAGIC     ON_HAND_INVENTORY_QTY FLOAT,
# MAGIC     DRFE_POS_ITEM_QTY FLOAT,
# MAGIC     DRFE_ERROR FLOAT,
# MAGIC     DRFE_LOAD_TS TIMESTAMP,
# MAGIC     MODEL_TYPE STRING,
# MAGIC     TEST_SET_MSE_PERFORMANCE FLOAT,
# MAGIC     HIGH_DOLLAR_SALES STRING,
# MAGIC     HIGH_FREQUENCY STRING,
# MAGIC     LOW_FREQUENCY STRING
# MAGIC         )
# MAGIC     USING DELTA
# MAGIC     PARTITIONED BY (RETAILER, CLIENT, COUNTRY_CODE)

# COMMAND ----------


