# Databricks notebook source
# MAGIC %sql
# MAGIC CREATE DATABASE IF NOT EXISTS RETAIL_FORECAST_ENGINE;

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS RETAIL_FORECAST_ENGINE.CHAMPION_MODELS
# MAGIC (
# MAGIC     RETAILER STRING,
# MAGIC     CLIENT STRING,
# MAGIC     ORGANIZATION_UNIT_NUM STRING,
# MAGIC     RETAILER_ITEM_ID STRING,
# MAGIC     MODEL_METADATA STRING,
# MAGIC     TRAINING_ID STRING,
# MAGIC     MODEL_ID STRING,
# MAGIC     MODEL_OBJECT BINARY,
# MAGIC     COLUMN_NAMES STRING,
# MAGIC     TEST_DAYS_COUNT INT,
# MAGIC     TRAIN_NON_ZERO_DAYS INT,
# MAGIC     TRAIN_DAYS_COUNT INT,
# MAGIC     TEST_SET_MASE_PERFORMANCE STRING,
# MAGIC     OBSERVED_DATE_RANGE_MIN DATE,
# MAGIC     OBSERVED_DATE_RANGE_MAX DATE,
# MAGIC     DATE_MODEL_TRAINED TIMESTAMP,
# MAGIC     MADE_CHAMPION_DATE TIMESTAMP
# MAGIC )
# MAGIC USING DELTA
# MAGIC PARTITIONED BY (RETAILER, CLIENT)

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS RETAIL_FORECAST_ENGINE.MODEL_TRAINING_RESULTS
# MAGIC (
# MAGIC     TRAINING_ID STRING,
# MAGIC     RETAILER STRING,
# MAGIC     CLIENT STRING,
# MAGIC     ORGANIZATION_UNIT_NUM STRING,
# MAGIC     RETAILER_ITEM_ID STRING,
# MAGIC     MODEL_METADATA STRING,
# MAGIC     COLUMN_NAMES STRING,
# MAGIC     TEST_NON_ZERO_DAYS INT,
# MAGIC     TEST_DAYS_COUNT INT,
# MAGIC     TRAIN_NON_ZERO_DAYS INT,
# MAGIC     TRAIN_DAYS_COUNT INT,
# MAGIC     MODEL_ID STRING,
# MAGIC     TEST_SET_MASE_PERFORMANCE FLOAT,
# MAGIC     OBSERVED_DATE_RANGE_MIN DATE,
# MAGIC     OBSERVED_DATE_RANGE_MAX DATE,
# MAGIC     DATE_MODEL_TRAINED TIMESTAMP
# MAGIC )
# MAGIC USING DELTA
# MAGIC PARTITIONED BY (RETAILER, CLIENT)

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS RETAIL_FORECAST_ENGINE.DRFE_FORECAST_BASELINE_UNIT
# MAGIC (
# MAGIC     HUB_ORGANIZATION_UNIT_HK STRING,
# MAGIC     HUB_RETAILER_ITEM_HK STRING,
# MAGIC     LOAD_TS TIMESTAMP,
# MAGIC     RECORD_SOURCE_CD STRING,
# MAGIC     BASELINE_POS_ITEM_QTY DECIMAL(15,2),
# MAGIC     MODEL_ID STRING,
# MAGIC     SALES_DT DATE
# MAGIC )
# MAGIC USING DELTA
# MAGIC PARTITIONED BY (SALES_DT)
